#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
主入口: 运行美股深度分析
用法:
    python run_analysis.py
    python run_analysis.py --temperature 0.1 --screen-temperature 0.4 --cooldown-days 2
"""

import os
import sys
import json
import re
import argparse
try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = lambda: None

from agent.llm_client import LLMClient
from agent.workflow import FinanceAnalysisWorkflow


def extract_summary(report: str, max_chars: int = 600) -> str:
    """从报告中提取精简摘要（跳过标题和表格）"""
    lines = []
    for line in report.split('\n'):
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith('#') or stripped.startswith('|') or stripped.startswith('---'):
            continue
        if stripped.startswith('```') or stripped.startswith('    '):
            continue
        lines.append(stripped)
        if len('\n'.join(lines)) >= max_chars:
            break
    summary = '\n'.join(lines)
    if len(summary) > max_chars:
        summary = summary[:max_chars].rsplit('\n', 1)[0] + '\n...'
    return summary


def generate_summary_md(data: dict, template_path: str, llm: object) -> str:
    """Call LLM to fill the summary template using JSON data."""
    with open(template_path, 'r', encoding='utf-8') as f:
        template = f.read()

    json_str = json.dumps(data, indent=2, ensure_ascii=False)

    system_prompts = [template]
    user_query = f"Here is the JSON data. Fill the template:\n\n{json_str}"

    result = llm.complete(
        system_prompts=system_prompts,
        user_query=user_query,
        temperature=0.15,
    )
    return result


def _save_summary_md(data: dict, md_path: str, llm: object = None) -> str:
    """Generate summary markdown via LLM from template + JSON data."""
    summary_md_path = md_path.replace('.md', '_summary.md')

    if llm:
        template_path = os.path.join(os.path.dirname(__file__), 'config', 'summary_model.md')
        try:
            md_content = generate_summary_md(data, template_path, llm)
            with open(summary_md_path, 'w', encoding='utf-8') as f:
                f.write(md_content)
            return summary_md_path
        except Exception as e:
            print(f"[Summary]  LLM summary generation failed: {e}, falling back to static")

    # Fallback: static summary (when LLM unavailable)
    lines = []
    macro = data.get('macro_judgment', {})
    lines.append(f"# 📋 US Stock Weekly — {data['report_date']}")
    lines.append("")
    lines.append(f"[box] **Macro**: {macro.get('fed_stance', '—')} | **Market**: {macro.get('market', '—')} [/box]")
    lines.append("")
    ind = data.get('indicators', {})
    if ind:
        lines.append("## 📊 Key Macro Data")
        lines.append("")
        lines.append("| Indicator | Value |")
        lines.append("|:---|:---|")
        for key, label in [('pce', 'Headline PCE (YoY)'), ('core_pce', 'Core PCE (YoY)'),
                           ('10y_yield', '10-Year Yield'), ('2y_yield', '2-Year Treasury'),
                           ('dxy', 'DXY')]:
            lines.append(f"| {label} | **{ind.get(key, '—')}** |")
        lines.append("")
    stocks = data.get('stocks', [])
    if stocks:
        lines.append("## 🔥 Top 3 Picks")
        lines.append("")
        color_rank = {'green': 0, 'yellow': 1, 'red': 2}
        ranked = sorted(stocks, key=lambda s: color_rank.get(s.get('recommendation_color', ''), 9))[:3]
        if ranked:
            lines.append("| # | Stock | Ticker | Price | Buy Range | Stop-Loss |")
            lines.append("|:---:|:---|:---:|:---:|:---|:---:|")
            medals = ['🥇', '🥈', '🥉']
            for i, s in enumerate(ranked):
                lines.append(
                    f"| {medals[i]} | **{s['name']}** | {s['symbol']} | "
                    f"{s.get('current_price', '—')} | "
                    f"{s.get('buy_range', '—')} | {s.get('stop_loss', '—')} |"
                )
            lines.append("")
    lines.append("## 🔗 Full Report")
    lines.append("")
    lines.append("→ {live_url}")
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by US Stock Deep Analysis Agent · {data['report_date']}*")

    with open(summary_md_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    return summary_md_path


def save_report_summary(report: str, md_path: str, html_path: str, llm: object = None) -> str:
    """
    Extract structured data from the full report and save as a tiny JSON summary
    alongside the report files. Returns the path to the summary JSON file.

    This is the file OpenClaw should read instead of the full 80KB+ report.
    """
    lines = report.split('\n')

    # --- Extract report date ---
    report_date = ""
    for line in lines[:10]:
        m = re.search(r'\*\*Date\*\*:\s*(.+)', line)
        if m:
            report_date = m.group(1).strip()
            break

    # --- Extract macro judgment (from the conclusion table) ---
    macro_judgment = {}
    for line in lines:
        m = re.match(r'\|\s*\*\*Fed Policy Stance\*\*\s*\|\s*\*\*(.+?)\*\*', line)
        if m:
            macro_judgment['fed_stance'] = m.group(1).strip()
            continue
        m = re.match(r'\|\s*\*\*US Dollar Index(?: Overall Judgment)?\*\*\s*\|\s*\*\*(.+?)\*\*', line)
        if m:
            macro_judgment['dollar'] = m.group(1).strip()
            continue
        m = re.match(r'\|\s*\*\*US Stock Market(?: Overall Judgment)?\*\*\s*\|\s*\*\*(.+?)\*\*', line)
        if m:
            macro_judgment['market'] = m.group(1).strip()
            continue

    # --- Extract macro summary paragraph ---
    macro_summary = ""
    in_macro_summary = False
    summary_lines = []
    for line in lines:
        if 'Macro Judgment Summary' in line and not line.startswith('## '):
            in_macro_summary = True
            # Check if the summary text starts on the same line (after colon)
            rest = re.split(r'\*\*Macro Judgment Summary\*\*\s*:?\s*', line, maxsplit=1)[-1]
            if rest:
                summary_lines.append(rest)
            continue
        if in_macro_summary:
            stripped = line.strip()
            if not stripped:
                break
            summary_lines.append(stripped)
    macro_summary = ' '.join(summary_lines)

    # --- Extract geopolitical headlines from Section II ---
    news_headlines = []
    in_geo_table = False
    for line in lines:
        if 'Top Geopolitical Headlines' in line:
            in_geo_table = True
            continue
        if in_geo_table:
            if not line.startswith('|'):
                continue  # skip blank lines and non-table content
            if line.startswith('| # |') or line.startswith('|:---'):
                continue
            if line.strip('| ') == '':
                break  # end of table
            cells = [c.strip() for c in line.strip().split('|') if c.strip()]
            if len(cells) >= 3 and cells[0].isdigit():
                # Strip bold markers for cleaner text
                headline = re.sub(r'\*+', '', cells[1]).strip()
                impact = re.sub(r'\*+', '', cells[2]).strip()
                news_headlines.append({"headline": headline, "impact": impact})

    # --- Extract Fed policy highlights from Section I ---
    fed_highlights = []
    # Extract key paragraphs: FOMC meeting summary, leadership transition, dot plot
    in_fed_section = False
    capture = False
    current_block = ""
    for line in lines:
        if '# I. 🏦 US Macro Policy & Federal Reserve' in line:
            in_fed_section = True
            continue
        if in_fed_section and (line.startswith('# II.') or line.startswith('## 📑') or line.startswith('# II')) :
            break
        if not in_fed_section:
            continue
        # Capture important narrative paragraphs (not tables, not headers)
        stripped = line.strip()
        if stripped.startswith('### ') or stripped.startswith('## '):
            if current_block.strip():
                fed_highlights.append(current_block.strip())
                current_block = ""
            # Capture the sub-header itself (e.g. "### The April 29 FOMC Meeting...")
            header_text = re.sub(r'^#+\s*', '', stripped)
            if any(kw in header_text.lower() for kw in ['fomc meeting', 'leadership transition', 'dot plot', 'macro regime']):
                fed_highlights.append(header_text)
            continue
        if stripped.startswith('|') or stripped.startswith('*Source') or stripped.startswith('*_Source'):
            continue
        if stripped.startswith('**') and ('Source' in stripped or 'Interpretation' in stripped):
            continue
        if not stripped:
            if current_block.strip():
                fed_highlights.append(current_block.strip())
                current_block = ""
            continue
        # Narrative text lines
        if not stripped.startswith('![') and not stripped.startswith('<!--'):
            current_block += " " + stripped
    if current_block.strip():
        fed_highlights.append(current_block.strip())

    # --- Extract key macro indicators from the data ---
    indicators = {}
    for line in lines:
        m = re.search(r'\|\s*30-Year Treasury Yield\s*\|\s*\*?\*?([\d.]+%)', line)
        if m: indicators['30y_yield'] = m.group(1)
        m = re.search(r'\|\s*10-Year Treasury Yield\s*\|\s*\*?\*?([\d.]+%)', line)
        if m: indicators['10y_yield'] = m.group(1)
        m = re.search(r'\|\s*2-Year Treasury Yield\s*\|\s*\*?\*?([\d.]+%)', line)
        if m: indicators['2y_yield'] = m.group(1)
        m = re.search(r'\|\s*DXY Dollar Index\s*\|\s*\*?\*?([\d.]+)', line)
        if m: indicators['dxy'] = m.group(1)
        m = re.search(r'\|\s*Headline PCE\s*\|\s*\*?\*?([+\-]?[\d.]+%)', line)
        if m: indicators['pce'] = m.group(1)
        m = re.search(r'\|\s*Core PCE\s*\|\s*\*?\*?([+\-]?[\d.]+%)', line)
        if m: indicators['core_pce'] = m.group(1)

    # --- Extract risk flags from the pre-screening table ---
    risk_flags = set()
    risk_levels = {}  # symbol -> "HIGH" / "MEDIUM" / "LOW"
    in_risk_table = False
    for line in lines:
        if '| Stock | 5-Day Change | 20-Day Change | Status | Notes |' in line:
            in_risk_table = True
            continue
        if in_risk_table:
            if not line.startswith('|') or line.strip('| ') == '':
                in_risk_table = False
                continue
            cells = [c.strip() for c in line.strip().split('|') if c.strip()]
            if len(cells) >= 4:
                status_cell = cells[3] if len(cells) > 3 else ""
                symbol = cells[0].strip() if len(cells) > 0 else ""
                if symbol and symbol not in ('Stock', '---'):
                    # Support both old binary and new 3-tier risk indicators
                    if 'HIGH' in status_cell.upper() or 'HIGH-RISK' in status_cell.upper():
                        risk_flags.add(symbol)
                        risk_levels[symbol] = "HIGH"
                    elif 'MEDIUM' in status_cell.upper():
                        risk_levels[symbol] = "MEDIUM"
                    elif 'LOW' in status_cell.upper():
                        risk_levels[symbol] = "LOW"

    # --- Extract stock data ---
    stocks = []
    # Stock section header: "## N. Company Name (TICKER)" or "## Stock N: Company Name (TICKER)"
    stock_headers = list(re.finditer(r'^##\s+(?:Stock\s+)?\d+[\.:]\s+(.+?)\(([A-Za-z.]+)\)', report, re.MULTILINE))

    # Also extract stock info from risk pre-screening table (for 5d/20d change)
    stock_risk_info = {}
    in_risk_table = False
    for line in lines:
        if '| Stock | 5-Day Change | 20-Day Change | Status | Notes |' in line:
            in_risk_table = True
            continue
        if in_risk_table:
            if not line.startswith('|') or line.strip('| -') == '':
                in_risk_table = False
                continue
            cells = [c.strip() for c in line.strip().split('|') if c.strip()]
            if len(cells) >= 4 and cells[0].strip():
                sym = cells[0].strip()
                if sym and sym not in ('Stock', '---'):
                    stock_risk_info[sym] = {
                        'pct_5d': cells[1].strip() if len(cells) > 1 else '',
                        'pct_20d': cells[2].strip() if len(cells) > 2 else '',
                    }

    for match in stock_headers:
        name_full = match.group(1).strip()
        symbol = match.group(2).strip()

        # Find the stock section boundaries (from this header to next stock or end)
        section_start = match.end()
        section_end = len(report)
        for next_match in stock_headers:
            if next_match.start() > match.start():
                section_end = next_match.start()
                break
        section = report[match.start():section_end]

        # Extract current price (try table format first, then bold-label fallback)
        price = ""
        m = re.search(r'\|\s*💰\s*Current Price\s*\|\s*\*?\*?\$?([\d,]+(?:\.\d+)?)', section)
        if not m:
            m = re.search('\\*\\*Current Price\\*\\*:\\s*(?:\\*\\*)?\\$?([\\d,]+(?:\\.\\d+)?)', section)
        if m:
            price = f"${m.group(1)}"

        # Extract market cap (try table format first)
        market_cap = ""
        m = re.search(r'\|\s*🏢\s*Market Cap\s*\|\s*(.+?)\s*\|', section)
        if not m:
            m = re.search(r'\*\*Market Cap\*\*:\s*(.+)', section)
        if m:
            market_cap = m.group(1).strip()
            # Strip bold markers from extracted text
            market_cap = re.sub(r'\*+', '', market_cap).strip()

        # Extract buy range (try table format first, supports $XXX-$XXX, en-dash, em-dash)
        buy_range = ""
        m = re.search(r'\|\s*🟢\s*Buy Range\s*\|\s*\*?\*?\$?([0-9.]+)\s*[–\-\—]\s*\$?([0-9.]+)', section)
        if not m:
            m = re.search('\\*\\*Buy Range\\*\\*:\\s*\\*\\*\\$?([0-9.]+)\\s*[–\\-—]\\s*\\$?([0-9.]+)', section)
        if m:
            buy_range = f"${m.group(1)}-${m.group(2)}"

        # Extract stop loss (try table format first)
        stop_loss = ""
        m = re.search(r'\|\s*🔴\s*Stop-Loss\s*\|\s*\*?\*?\$?([\d.]+)', section)
        if not m:
            m = re.search('\\*\\*Stop-Loss\\*\\*:\\s*\\*\\*\\$?([\\d.]+)', section)
        if m:
            stop_loss = f"${m.group(1)}"

        # Extract trading recommendation (try table badge first, then bold-label, then anywhere in section)
        recommendation = ""
        recommendation_color = ""
        # Try table format: | ⚡ Recommendation | [badge:color]Text[/badge] |
        m = re.search(r'\|\s*⚡\s*Recommendation\s*\|\s*\[badge:(\w+)\](.+?)\[/badge\]', section)
        if m:
            recommendation_color = m.group(1)
            recommendation = m.group(2).strip()
        # Try bold-label format: **Trading Recommendation**: [badge:color]Text[/badge]
        if not recommendation:
            m = re.search(r'\*\*Trading Recommendation\*\*:\s*\*\*(.+?)\*\*', section)
            if m:
                raw_rec = m.group(1).strip()
                badge_m = re.search(r'\[badge:(\w+)\](.+?)\[/badge\]', raw_rec)
                if badge_m:
                    recommendation_color = badge_m.group(1)
                    recommendation = badge_m.group(2).strip()
                else:
                    recommendation = raw_rec
        # Fallback: any badge in section
        if not recommendation:
            m = re.search(r'\[badge:(\w+)\](Priority Buy|Wait for Pullback|Not Recommended)\[/badge\]', section)
            if m:
                recommendation_color = m.group(1)
                recommendation = m.group(2).strip()

        risk_info = stock_risk_info.get(symbol, {})

        stocks.append({
            "symbol": symbol,
            "name": name_full,
            "current_price": price,
            "market_cap": market_cap,
            "recommendation": recommendation,
            "recommendation_color": recommendation_color,
            "buy_range": buy_range,
            "stop_loss": stop_loss,
            "pct_change_5d": risk_info.get('pct_5d', ''),
            "pct_change_20d": risk_info.get('pct_20d', ''),
            "risk_flag": symbol in risk_flags,
            "risk_level": risk_levels.get(symbol, ""),
        })

    summary_data = {
        "report_date": report_date,
        "macro_judgment": macro_judgment,
        "macro_summary": macro_summary,
        "indicators": indicators,
        "stocks": stocks,
        "news_headlines": news_headlines,
        "fed_highlights": fed_highlights,
        "files": {
            "markdown": os.path.abspath(md_path),
            "html": os.path.abspath(html_path),
        },
        "stock_count": len(stocks),
    }

    # Start persistent HTTP server and get a working URL (before LLM summary)
    summary_path = md_path.replace('.md', '_summary.json')
    try:
        from web_renderer import ensure_report_url
        html_filename = os.path.basename(html_path)
        output_dir = os.path.dirname(os.path.abspath(html_path))
        live_url = ensure_report_url(output_dir, html_filename)
        summary_data["live_url"] = live_url
    except Exception:
        summary_data["live_url"] = os.path.abspath(html_path)

    # Save JSON
    with open(summary_path, 'w', encoding='utf-8') as f:
        json.dump(summary_data, f, indent=2, ensure_ascii=False)
    summary_kb = os.path.getsize(summary_path) / 1024
    print(f"\n[Summary]  报告摘要JSON已保存: {summary_path} ({summary_kb:.1f} KB)")

    # Save Markdown summary via LLM
    summary_md_path = _save_summary_md(summary_data, md_path, llm=llm)
    summary_md_kb = os.path.getsize(summary_md_path) / 1024 if os.path.exists(summary_md_path) else 0
    print(f"[Summary]  报告摘要Markdown已保存: {summary_md_path} ({summary_md_kb:.1f} KB)")
    print(f"[Link]  工作链接（可点击）: {summary_data['live_url']}")
    print(f"[Tip]  OpenClaw 使用此链接展示完整报告")

    return summary_path


def main():
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser(description="Run US Stock Deep Analysis")
    parser.add_argument("--temperature", type=float, default=0.1,
                        help="Base temperature for LLM (default: 0.1)")
    parser.add_argument("--screen-temperature", type=float, default=0.4,
                        help="Temperature for stock screening phase (default: 0.4)")
    parser.add_argument("--cooldown-days", type=int, default=3,
                        help="Days before a dropped stock can return (default: 3)")
    args = parser.parse_args()

    # 加载环境变量
    load_dotenv()  # 从 .env 文件加载

    # 从环境变量读取LLM配置
    BASE_URL = os.environ.get("LLM_BASE_URL", "https://ark.cn-beijing.volces.com/api/coding/v3")
    API_KEY = os.environ.get("LLM_API_KEY")
    MODEL = os.environ.get("LLM_MODEL", "ark-code-latest")

    if not API_KEY:
        print("[X]  请设置 LLM_API_KEY 环境变量（在 .env 文件中）")
        print("示例: LLM_API_KEY=ark-xxxxxxx")
        sys.exit(1)

    # 初始化LLM客户端
    llm = LLMClient(
        base_url=BASE_URL,
        api_key=API_KEY,
        model=MODEL,
        context_window=256000,
        max_tokens=32000,
        enable_prompt_caching=True,
    )

    # 初始化工作流
    workflow = FinanceAnalysisWorkflow(
        llm_client=llm,
        config_dir="config"
    )

    # 运行
    try:
        report, path = workflow.run(
            output_dir="output",
            temperature=args.temperature,
            screen_temperature=args.screen_temperature,
            cooldown_days=args.cooldown_days,
        )
        print("\n" + "=" * 60)
        print(f"[OK]  工作流完成!")
        print(f"[File]  报告位置: {path}")
        print("=" * 60)

        # 保存结构化摘要JSON（供OpenClaw快速读取）
        html_path = path.replace('.md', '.html')
        save_report_summary(report, path, html_path, llm=llm)

        # 输出精简摘要
        summary = extract_summary(report, max_chars=600)
        if summary:
            print("\n[Summary]  报告摘要:")
            print(summary)
    except KeyboardInterrupt:
        print("\n\n[Stop]   用户中断")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n[X]  错误: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
